version: 0.1
frontend:
  phases:
    install:
      runtime-versions:
        nodejs: 10
      commands:
        - npm install

    build:
      commands:
        - npm run build

  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
