version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm ci
  build:
    commands:
      - npm run build
      - npm run test:lh:ci
  post_build:
    commands:
      - aws s3 sync --exclude '*.html' --delete dist/ s3://${bucket_name} --cache-control max-age=31536000
      - aws s3 sync --include '*.html' --delete dist/ s3://${bucket_name} --cache-control no-cache
cache:
  paths:
    - "/root/.npm/**/*"
    - ".gulp-cache/**/*"
