version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  build:
    commands:
      - npm run build
  upload:
    commands:
      - aws s3 sync --delete dist/ s3://${bucket_name} --cache-control max-age=3600
  post_build:
    commands:
      - echo 'Invalidating distribution cache'
      - aws cloudfront create-invalidation --distribution-id ${distribuition_id} --paths "/*"
