version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync --exclude '*.html' --delete dist/ s3://${bucket_name} --cache-control max-age=31536000
      - aws s3 sync --include '*.html' --delete dist/ s3://${bucket_name} --cache-control no-cache
      - echo 'Invalidating distribution cache'
      - aws cloudfront create-invalidation --distribution-id ${distribution_id} --paths "/*"
cache:
  paths:
    - "/root/.npm/**/*"
    - ".gulp-cache/**/*"
