name: Lighthouse
on: [push, pull_request]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Install
        run: npm ci

      - name: build
        run: npm run build

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: "./lighthouserc.json"
          temporaryPublicStorage: true
          uploadArtifacts: true
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

